abstract Item {
 + ItemType type
 + Item(ItemType type)
 + void use(room room, Player)
}

class FFP2 extends Item {
 + Time immunityLength
 + void use(room room, Player)
}
class Camembert extends Item {
 + void use(room room, Player)
}
class Transistor extends Item {
 + Transistor pair
 + room room
 + void use(room room, Player)
}


enum ItemType {
    FFP2
    Camembert
    Transistor
    SlideRule
    TVSZ
    Glass
    Rug
}